# Generated by Django 4.1 on 2022-08-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.CharField(max_length=300)),
                ('aboutme2', models.CharField(max_length=300)),
                ('PYTHON1', models.CharField(max_length=20)),
                ('PYTHON', models.CharField(max_length=300)),
                ('BRAND_IDENTITY1', models.CharField(max_length=20)),
                ('BRAND_IDENTITY', models.CharField(max_length=300)),
                ('Admin1', models.CharField(max_length=20)),
                ('Admin22', models.CharField(max_length=300)),
                ('TELEGRAM_BOt1', models.CharField(max_length=20)),
                ('TELEGRAM_BOt', models.CharField(max_length=300)),
                ('DATABASE1', models.CharField(max_length=20)),
                ('DATABASE', models.CharField(max_length=300)),
                ('Github1', models.CharField(max_length=20)),
                ('Github', models.CharField(max_length=300)),
                ('GETINTOUCH', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('gmail', models.CharField(max_length=50)),
                ('copyright', models.CharField(max_length=50)),
                ('design', models.CharField(max_length=50)),
                ('adham', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('django', models.CharField(max_length=50)),
                ('djangorestapi', models.CharField(max_length=50)),
                ('documentation', models.CharField(max_length=50)),
                ('pythoncoding', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
                ('telegramchanel', models.CharField(max_length=50)),
                ('telegrambot', models.CharField(max_length=50)),
                ('fullbot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.news')),
            ],
        ),
    ]
